[tool.black]
target-version = ['py312']

[tool.mypy]
python_version = "3.12"
disallow_untyped_calls = true
disallow_subclassing_any = true
no_implicit_optional = true
strict_equality = true
warn_return_any = true
warn_unreachable = true
exclude = [
    'manage\.py'
]
