# Generated by Django 5.0.4 on 2024-05-06 06:37

import api.models.game_record
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.game_record.random_id,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(default=api.models.game_record.current_time),
                ),
                ("game_mode", models.CharField(max_length=64)),
                ("character_name", models.CharField(max_length=512)),
                ("tile", models.CharField(max_length=256)),
                ("score", models.BigIntegerField()),
                ("turns", models.BigIntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(fields=["id"], name="api_gamerec_id_20d428_idx"),
                    models.Index(
                        fields=["created"], name="api_gamerec_created_8582d2_idx"
                    ),
                ],
            },
        ),
    ]
