version: '3'

services:
  web:
    image: 'hagiography-web:latest'
    hostname: 'web.local'
    build:
      context: ..
      dockerfile: ./deploy/webserver/Dockerfile
      args:
        USER_UID: "1000"
    ports:
      - '8000:80'
    environment:
      DEVELOPMENT: "1"
    volumes:
      - ../webapp:/srv:rw
    networks:
      - internal

  apiserver:
    image: 'hagiography-api:latest'
    hostname: 'api.local'
    build:
      context: ..
      dockerfile: ./deploy/apiserver/Dockerfile
    environment:
      GUNICORN_RELOAD: "1"
    volumes:
      - ../server:/var/www/server:ro
    networks:
      - internal


networks:
  internal:
